### ISSUE TITLE
Pre populate feeds

### ISSUE THREAD

**Issue by petesavva** [EvgenyKarkan/Feeds4U#23]
Good afternoon Evgeny,
I didn't know any other way to contact you, I hope this is ok.

Feeds4U is a nice app, I really would like to incorporate it in my own app. However (I am new to iOS programming) I was wondering if you could help me out and show me how to add RSS in the package, so when the user downloads the app there are already 20-25 feeds pre installed. 

Thank you.

**Comment by EvgenyKarkan** [comment]
Hey, sorry, hope you already figured it out, closing.
